apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: flux-system # ← Changed from istio-system
spec:
  targetNamespace: istio-system # ← Add this line
  interval: 1m
  chart:
    spec:
      chart: istiod
      version: 1.17.2
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
