apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: flux-system
spec:
  targetNamespace: istio-system
  interval: 1m
  chart:
    spec:
      chart: istiod
      version: 1.17.2
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  values:
    pilot:
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 1Gi
