apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ingressgateway
  namespace: flux-system
spec:
  targetNamespace: istio-system
  interval: 5m
  dependsOn:
    - name: istiod
      namespace: flux-system
  chart:
    spec:
      chart: gateway
      version: 1.17.2
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  install:
    createNamespace: true
  values:
    service:
      type: LoadBalancer
