apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: flux-system # ← Changed from istio-system
spec:
  targetNamespace: istio-system # ← Add this line
  interval: 1m
  chart:
    spec:
      chart: base
      version: 1.17.2
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
