apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: petclinic
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ./app/helm/petclinic
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: 238108322530.dkr.ecr.us-east-1.amazonaws.com/my-devops-ecr
      tag: 93f5fa3af24435373e885f9913b0d8b0e85efc1a
    service:
      type: LoadBalancer
